services:
    db:
        image: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=Afpa1234

    web:
        build: .
        ports:
            - 80:80
            # - 443:443
        volumes:
            - .:/var/www
       